export interface CouplingFilter {
  slug: string;
  label: string;
  images: string[];
}

// Curated coupling filter terms. Each term links to /filter/{slug}/ and shows
// a filtered masonry of the images listed below.
// Auto-generated by the in-page filter editor.
export const couplingFilters = [
  {
    slug: "circle-square-circle",
    label: "Circle-Square-Circle",
    images: ["https://pub-e0d304e4d3564adbb6c3cbf768403529.r2.dev/cargo-p-delta.png","https://pub-e0d304e4d3564adbb6c3cbf768403529.r2.dev/cargo-p-delta-01.png","https://pub-e0d304e4d3564adbb6c3cbf768403529.r2.dev/cargo-p-delta-02.png","https://pub-e0d304e4d3564adbb6c3cbf768403529.r2.dev/project-1-1.jpg","https://pub-e0d304e4d3564adbb6c3cbf768403529.r2.dev/project-1-2.jpg","https://pub-e0d304e4d3564adbb6c3cbf768403529.r2.dev/20251106-nano-banana-2025-11-06T12-03-53.jpg","https://pub-e0d304e4d3564adbb6c3cbf768403529.r2.dev/20251106-nano-banana-2025-11-06T11-31-06.jpg"],
  },
  {
    slug: "among-the-trees",
    label: "Among the Trees",
    images: ["https://pub-e0d304e4d3564adbb6c3cbf768403529.r2.dev/cargo-xiaobo.png","https://pub-e0d304e4d3564adbb6c3cbf768403529.r2.dev/cargo-xiaobo-02.png","https://pub-e0d304e4d3564adbb6c3cbf768403529.r2.dev/cargo-xiaobo-03.png","https://pub-e0d304e4d3564adbb6c3cbf768403529.r2.dev/project-2-1.jpg","https://pub-e0d304e4d3564adbb6c3cbf768403529.r2.dev/project-2-2.jpg"],
  },
  {
    slug: "infra",
    label: "Infra",
    images: ["https://pub-e0d304e4d3564adbb6c3cbf768403529.r2.dev/%E6%88%AA%E5%B1%8F2026-07-13%2017.21.15.png","https://pub-e0d304e4d3564adbb6c3cbf768403529.r2.dev/20251106-nano-banana-2025-11-06T11-48-22.jpg","https://pub-e0d304e4d3564adbb6c3cbf768403529.r2.dev/20251106-nano-banana-2025-11-06T12-44-15.jpg"],
  },
];
